version: '3'

services:
  kubo:
    image: ipfs/kubo
    container_name: kubo
    restart: always
    environment:
      - IPFS_PROFILE=lowpower
    volumes:
      - ./kubo/ipfs:/data/ipfs
      - ./kubo/export:/export
    ports:
      - 4001:4001
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080