version: '3'

services:
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    volumes:
      - ./v2ray:/etc/v2ray
    entrypoint: v2ray run -config=/etc/v2ray/config.json
  
  caddy:
    image: caddy:2.6-alpine
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - WSPATH=${WSPATH}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/Caddyfile:ro
    entrypoint: [caddy,run,--config,/Caddyfile]
