version: '3'

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: always
    volumes:
      - ./v2ray:/etc/v2ray
    entrypoint: v2ray run -config=/etc/v2ray/config.json

  kubo:
    image: ipfs/kubo
    container_name: kubo
    restart: always
    environment:
      - IPFS_PROFILE=lowpower
    volumes:
      - ./kubo/ipfs:/data/ipfs
      - ./kubo/export:/export
    ports:
      - 4001:4001
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080
  
  caddy:
    image: caddy:2.6-alpine
    container_name: caddy
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - WSPATH=${WSPATH}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/Caddyfile:ro
    entrypoint: [caddy,run,--config,/Caddyfile]
